# Cấu hình thời gian chờ (cooldown) cho food
# sun.countdown.food.<vip>
food-countdown:
  vip2: 30
  vip3: 20
  vip4: 15
  vip5: 10

# sun.countdown.food.<vip>
heal-countdown:
  vip3: 720  # 12 phút cooldown
  vip4: 480  # 8 phút cooldown
  vip5: 300  # 5 phút cooldown

# Cấu hình countdown cho fly
fly-countdown:
  vip0: 30
  vip1: 20
  vip2: 15
  vip3: 10

# Cấu hình thời gian bay (usage time)
fly-usage-time:
  vip0: 30
  vip1: 60
  vip2: 120
  vip3: 180
