name: Sunflower
main: Sunflower.MainPlugin
version: 1.1.4
api-version: 1.19
commands:
  fly:
    description: Toggle fly mode
    usage: /fly
  food:
    description: Restore hunger
    usage: /food
  freload:
    description: Reload plugin configuration
    usage: /freload
  heal:
    description: Heal yourself to full health.
    usage: /heal
