food:
  - permission: "sunflower.food.default"
    cooldown: 40  # Thời gian cooldown cho quyền này
  - permission: "sunflower.food.vip1"
    cooldown: 50  # Thời gian cooldown cho quyền này

fly:
  - permission: "sunflower.fly"
    countdown: 61  # Thời gian countdown cho quyền này
    usage_time: 15  # Thời gian sử dụng bay cho quyền này
  - permission: "sunflower.fly.vip1"
    countdown: 51
    usage_time: 20
