#               Quyền liên quan đến lệnh /food
# sun.countdown.food.<vip>
# sun.food.bypass	Bỏ qua cooldown khi sử dụng /food
food-countdown:
  vip0: 300
  vip1: 180
  vip2: 108
  vip3: 65
  vip4: 39
  vip5: 23

#               Quyền liên quan đến lệnh /heal
# sun.countdown.heal.<vip>
# sun.heal.bypass	Bỏ qua cooldown khi sử dụng /heal
heal-countdown:
  vip0: 420
  vip1: 252
  vip2: 151
  vip3: 91
  vip4: 55
  vip5: 33

#               Cấu hình countdown cho fly
# sun.countdown.fly.<vip>
fly-time: 60  # ⏳ Thời gian bay mặc định cho mọi người chơi (giây)
fly-countdown:
  vip0: 540
  vip1: 432
  vip2: 259
  vip3: 155
  vip4: 93
  vip5: 56

# Cấu hình thời gian bay (usage time)
fly-usage-time:
  vip0: 42
  vip1: 70
  vip2: 116
  vip3: 194
  vip4: 324
  vip5: 540

#           Quyền đặc biệt cho quản trị viên (Admin)
# sun.admin	        Cho phép quản trị viên reload plugin bằng lệnh /freload
# sun.fly.bypass	Bỏ qua countdown khi sử dụng /fly
# sun.food.bypass	Bỏ qua cooldown khi sử dụng /food